# Generated by Django 3.0.3 on 2020-09-08 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('passenger', models.IntegerField(null=True)),
                ('StartLocation', models.CharField(choices=[('Kuniyamuthur', 'Kuniyamuthur'), ('Ukkadam', 'Ukkadam'), ('Gandhipuram', 'Gandhipuram'), ('Sundharapuram', 'Sundharapuram')], max_length=255, null=True)),
                ('ToLocation', models.CharField(choices=[('Kuniyamuthur', 'Kuniyamuthur'), ('Ukkadam', 'Ukkadam'), ('Gandhipuram', 'Gandhipuram'), ('Sundharapuram', 'Sundharapuram')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('Location', models.CharField(blank=True, choices=[('Kuniyamuthur', 'Kuniyamuthur'), ('Ukkadam', 'Ukkadam'), ('Gandhipuram', 'Gandhipuram'), ('Sundharapuram', 'Sundharapuram')], max_length=255, null=True)),
                ('lic_no', models.IntegerField(blank=True, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
