# Generated by Django 3.0.3 on 2020-09-10 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookingapp', '0002_remove_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driver',
            name='Location',
            field=models.CharField(choices=[('Kuniyamuthur', 'Kuniyamuthur'), ('Ukkadam', 'Ukkadam'), ('Gandhipuram', 'Gandhipuram'), ('Sundharapuram', 'Sundharapuram')], max_length=255, null=True),
        ),
    ]
