# Generated by Django 3.0.3 on 2020-09-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_auto_20200910_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='date_created',
        ),
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
