# Generated by Django 3.0.3 on 2020-09-10 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0005_driver_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
    ]
